# -*- coding: utf-8 -*-
"""Contenu — les 12 fiches ingrédients (+ 1 bonus)."""

# Champs : num, nom, sci, famille, preuve, cout, pose, pourquoi, cible[], qte[], recette_titre,
# recette[], recette_note, etapes[4], freq[(titre, sous)], precautions[], erreurs[3], conservation, retiens

FICHES = [
dict(num=1, nom="L'huile de coco", sci="Cocos nucifera · huile vierge, pressée à froid",
     famille="Huiles de base", preuve="etaye", cout="≈ 50 à 80 FCFA l'application", pose="30 min (ou une nuit)",
     pourquoi="C'est la seule huile de cuisine courante qui entre <b>dans</b> le cheveu. Ses acides gras sont "
              "courts et droits : ils se glissent entre les écailles, se logent dans la fibre et y laissent un film "
              "qui repousse l'eau. Résultat : quand vous lavez, le cheveu gonfle moins, ses écailles se soulèvent "
              "moins, et il perd beaucoup moins de protéines. Dans l'étude de référence (Rele &amp; Mohile, 2003), "
              "une application avant le shampooing a réduit la perte de protéines de la fibre de près de 40 % — "
              "sur cheveu sain comme sur cheveu abîmé. C'est le geste le plus rentable de tout le guide.",
     cible=["Tous types de cheveux", "Porosité haute", "Cheveux abîmés par la chaleur ou le défrisage", "Avant chaque shampooing"],
     qte=[("Cheveux courts (moins de 10 cm)", "1 c. à café", "≈ une noisette"),
          ("Cheveux mi-longs (10 à 25 cm)", "2 c. à café", "≈ deux noisettes"),
          ("Cheveux longs (plus de 25 cm)", "1 c. à soupe", "≈ une grosse noix")],
     qte_note="Dose pour un <b>pré-poo</b> (soin avant lavage). Pour un bain d'huile chaud, doublez la quantité.",
     recette_titre="Le pré-poo qui sauve les longueurs",
     recette=["1 c. à soupe d'huile de coco (cheveux longs ; 2 c. à café pour cheveux courts)",
              "1 c. à café de miel pur",
              "3 gouttes d'huile essentielle de romarin (facultatif — jamais plus)"],
     recette_note="Mélangez dans un petit bol. Si l'huile est solide, posez le bol 3 minutes dans de l'eau chaude. "
                  "Jamais sur le feu.",
     etapes=["Appliquez sur cheveux <b>secs</b>, en quatre sections, en commençant par les pointes.",
             "Massez le crâne du bout des doigts pendant 2 minutes, sans gratter.",
             "Couvrez d'un bonnet plastique. Posez 30 minutes — ou toute la nuit si vos cheveux sont très secs.",
             "Lavez au shampooing doux, puis enchaînez sur votre masque habituel."],
     freq=[("Avant chaque shampooing", "1 fois par semaine en routine normale"),
           ("Bain d'huile chaud", "1 fois par 15 jours"),
           ("Cheveux très secs", "peut rester toute la nuit"),
           ("Crâne gras", "longueurs seulement, pas le crâne")],
     precautions=["Elle durcit sous 24 °C : c'est normal, tiédissez-la pour la prélever.",
                  "En couche épaisse et répétée sur le crâne, elle peut boucher les pores et provoquer des boutons.",
                  "Allergie rare à la noix de coco : testez une goutte sur le pli du coude 24 h avant la première fois."],
     erreurs=["En mettre « beaucoup » pour que ça marche mieux : au-delà de la dose, ça ne pénètre pas plus.",
              "L'appliquer sur cheveux mouillés par impatience : en pré-poo, c'est sur cheveux secs qu'elle pénètre le mieux.",
              "La laisser des heures sur un crâne déjà gras : 30 minutes suffisent."],
     conservation="1 an et demi à 2 ans, à l'abri de la chaleur.",
     retiens="30 minutes et 50 FCFA qui sauvent de la longueur à chaque lavage."),

dict(num=2, nom="Le beurre de karité", sci="Vitellaria paradoxa · non raffiné, du Nord-Bénin",
     famille="Beurres", preuve="tradition", cout="≈ 10 à 20 FCFA l'application", pose="immédiat (finition) · 20 min en masque",
     pourquoi="Le karité est un gras lourd : ses molécules sont trop grosses pour entrer dans le cheveu. Il ne nourrit "
              "donc pas — il <b>scelle</b>. Appliqué sur un cheveu encore humide, il forme un film souple qui empêche "
              "l'eau de s'évaporer et protège la fibre du vent, du soleil et du harmattan. C'est aussi un excellent "
              "lubrifiant : le cheveu glisse, se casse moins au coiffage. Un beurre de karité non raffiné coûte "
              "presque rien et fait le travail d'un beurre importé à 6 000 FCFA.",
     cible=["Cheveux 4A, 4B, 4C", "Cheveux très secs", "Porosité haute", "Saison sèche et harmattan", "Pointes abîmées"],
     qte=[("Cheveux courts (moins de 10 cm)", "1 noisette", "≈ 2 g"),
          ("Cheveux mi-longs (10 à 25 cm)", "1 noix", "≈ 5 g"),
          ("Cheveux longs (plus de 25 cm)", "2 noix", "≈ 10 g")],
     qte_note="Par application, sur cheveu <b>humide</b>. Jamais plus de deux noix, même sur cheveux longs.",
     recette_titre="Le beurre de karité fouetté (3 ingrédients)",
     recette=["4 c. à soupes de karité non raffiné (≈ 40 g)",
              "2 c. à soupes d'huile de coco ou d'olive",
              "1 c. à café d'huile de ricin"],
     recette_note="Battez 5 minutes au fouet ou au mixeur, jusqu'à obtenir une mousse blanche et légère. "
                  "Se garde 3 mois dans un petit pot propre, à l'abri de la chaleur.",
     etapes=["Prélevez une noix de beurre et faites-la fondre entre vos paumes — jamais au feu.",
             "Appliquez sur cheveu <b>essoré mais encore humide</b> : c'est cette eau que le beurre va retenir.",
             "Travaillez mèche par mèche, pointes d'abord, peu de produit et bien réparti.",
             "Coiffez (tresses, twists, afro). N'ajoutez pas de beurre « pour que ça brille » : la brillance vient du cheveu hydraté."],
     freq=[("Après chaque hydratation", "1 à 2 fois par semaine"),
           ("En saison sèche (harmattan)", "¼ de noisette sur les pointes, tous les 2 jours"),
           ("En masque avant lavage", "1 fois par mois maximum"),
           ("Plafond à ne pas dépasser", "2 noix par application")],
     precautions=["Sur un crâne gras ou à pellicules grasses, réservez-le aux longueurs.",
                  "Trop de karité « étouffe » le cheveu : il ne prend plus l'eau et reste gras au toucher.",
                  "Le « karité » blanc et parfumé du commerce contient souvent de la paraffine : préférez le beurre beige, à l'odeur de noix."],
     erreurs=["L'appliquer sur cheveu sec : vous posez un couvercle sur une casserole vide.",
              "Le chauffer au feu direct : il perd ses insaponifiables. Bain-marie tiède, pas plus.",
              "Superposer huile + beurre sur cheveu sec : cheveu gras au toucher, assoiffé à l'intérieur."],
     conservation="12 à 24 mois, à l'ombre et sous 30 °C. Il rancit s'il jaunit fortement et sent l'amer.",
     retiens="Eau d'abord, beurre ensuite. Toujours dans cet ordre."),

dict(num=3, nom="L'huile de ricin", sci="Ricinus communis · « huile de palme de ricin », ricin noir",
     famille="Huiles actives", preuve="prometteur", cout="≈ 20 à 30 FCFA l'application", pose="5 min de massage",
     pourquoi="Très visqueuse, l'huile de ricin reste autour du cheveu et l'enrobe : le cheveu paraît plus épais, "
              "plus lourd, mieux tenu. C'est utile sur cheveux fins et sur une lisière fragilisée. Mais il faut le dire "
              "clairement : <b>elle ne fait pas pousser les cheveux plus vite</b>. Aucune étude ne le démontre. "
              "La pousse est décidée par le follicule, dans le crâne — pas par ce qu'on pose dessus.",
     cible=["Cheveux fins", "Lisière et racines fragiles", "Tempes clairsemées", "Frisottis à discipliner"],
     qte=[("Pour tout le crâne (toutes longueurs)", "½ c. à café", "≈ 2,5 ml"),
          ("Huile fluide à ajouter (coco ou olive)", "1 à 2 c. à café", "1 part de ricin pour 2 parts d'huile"),
          ("Sur la lisière uniquement", "½ c. à café diluée", "au bout du doigt")],
     qte_note="<b>Toujours diluée.</b> Pure, elle colle, démange et arrache les cheveux au démêlage.",
     recette_titre="L'huile de massage pour le crâne et la lisière",
     recette=["½ c. à café d'huile de ricin",
              "1 c. à café d'huile de coco ou d'olive",
              "3 gouttes d'huile essentielle de romarin (facultatif)"],
     recette_note="Préparez la dose dans le creux de la main, pas dans le flacon : vous éviterez de contaminer "
                  "toute la bouteille.",
     etapes=["Versez les ½ c. à café de ricin dans la paume, ajoutez l'huile fluide, mélangez.",
             "Massez le crâne du bout des doigts pendant 5 minutes, en petits cercles, sans frotter la lisière.",
             "Insistez sur les tempes et la nuque — jamais sur une zone irritée ou douloureuse.",
             "Laissez en place jusqu'au prochain lavage : il n'y a pas besoin de rincer le jour même."],
     freq=[("Massage du crâne", "1 fois par semaine maximum"),
           ("Lisière en convalescence", "2 à 3 fois par semaine, très diluée"),
           ("Cheveux fins", "1 fois par 15 jours"),
           ("Deux jours de suite", "jamais")],
     precautions=["Crâne gras ou pellicules grasses : évitez le ricin sur le crâne.",
                  "Si boutons, démangeaisons ou tension apparaissent : arrêtez deux semaines.",
                  "Enceinte ou allaitante : par simple prudence, demandez l'avis de votre sage-femme avant un usage régulier."],
     erreurs=["En attendre des centimètres de pousse : c'est le mythe le plus vendu du marché.",
              "La laisser poser plusieurs jours : elle colle, ramasse la poussière et bloque le cuir chevelu.",
              "En mettre partout sur un crâne déjà gras : les longueurs suffisent."],
     conservation="1 à 2 ans, au frais et à l'abri de la lumière.",
     retiens="Le ricin gaine et fait briller. Il n'engraisse pas la terre : il ne fait pas pousser."),

dict(num=4, nom="L'huile d'olive", sci="Olea europaea · vierge ou extra-vierge",
     famille="Huiles de base", preuve="prometteur", cout="≈ 90 FCFA l'application", pose="20 à 30 min (bain d'huile)",
     pourquoi="Ses acides gras s'insèrent partiellement dans la fibre et rendent la cuticule plus souple : le cheveu "
              "s'étire sans casser et se démêle plus facilement. Plus lourde que l'huile de coco, elle convient aux "
              "cheveux très secs et aux porosités basses qui « refusent » l'eau. Vérifiez l'étiquette : beaucoup "
              "d'huiles vendues comme « olive » sur les marchés sont coupées au tournesol, qui ne pénètre pas.",
     cible=["Cheveux secs et rêches", "Porosité basse", "Cheveux épais ou denses", "Saison sèche"],
     qte=[("Cheveux courts (moins de 10 cm)", "1 c. à café", "≈ une noisette"),
          ("Cheveux mi-longs (10 à 25 cm)", "1 c. à soupe", "≈ une grosse noix"),
          ("Cheveux longs (plus de 25 cm)", "2 c. à soupes", "≈ deux grosses noix")],
     qte_note="Dose pour un <b>bain d'huile chaud</b>. Pour un simple pré-poo, divisez par deux.",
     recette_titre="Le bain d'huile chaud olive-miel",
     recette=["2 c. à soupes d'huile d'olive",
              "1 c. à soupe de miel",
              "2 gouttes d'huile essentielle de romarin (facultatif)"],
     recette_note="Tiédissez au bain-marie : l'huile doit être <b>tiède sur votre poignet</b>, jamais chaude. "
                  "Une huile brûlante cuit le cheveu et brûle le crâne.",
     etapes=["Tiédissez l'huile 3 minutes dans un bol d'eau chaude.",
             "Appliquez en quatre sections, des pointes vers les racines.",
             "Bonnet plastique + serviette chaude par-dessus : 20 à 30 minutes.",
             "Lavez au shampooing doux, puis masque hydratant comme d'habitude."],
     freq=[("Routine normale", "1 fois par semaine"),
           ("Cheveux fins", "1 fois par 15 jours"),
           ("Avant une pose de tresses", "1 fois, la semaine d'avant"),
           ("Crâne irrité", "on reporte")],
     precautions=["Elle alourdit : sur cheveux fins, préférez l'huile de coco.",
                  "Si le crâne est gras ou pelliculaire, gardez-la sur les longueurs.",
                  "Une huile « d'olive » coupée au tournesol ne pénètre pas : lisez l'étiquette, ou goûtez-la (une vraie huile d'olive pique un peu)."],
     erreurs=["La chauffer à la casserole jusqu'à ce qu'elle fume.",
              "La laisser poser 3 heures « pour que ça pénètre » : 30 minutes suffisent.",
              "La choisir parfumée : les arômes n'apportent rien et peuvent irriter."],
     conservation="18 à 24 mois, à l'abri de la lumière et de la chaleur.",
     retiens="Elle prépare le cheveu avant qu'on le manipule. Un cheveu souple passe dans le peigne."),

dict(num=5, nom="Le gombo", sci="Abelmoschus esculentus · okra, gumbo",
     famille="Gels et mucilages", preuve="tradition", cout="≈ 50 FCFA l'application", pose="15 à 20 min",
     pourquoi="Le gombo libère un <b>mucilage</b> : une substance glissante qui gaine la tige du cheveu et fait "
              "tomber le frottement entre les mèches. Résultat : on démêle sans arracher, et le cheveu garde son eau "
              "plus longtemps. C'est l'ancêtre local de l'après-shampooing — en mieux, parce qu'il ne laisse ni "
              "silicone ni film gras. C'est aussi le soin le plus efficaces pour démêler les cheveux des enfants.",
     cible=["Tous types", "Le roi du 4C", "Cheveux des enfants", "Après une dépose de tresses"],
     qte=[("Cheveux courts (moins de 10 cm)", "1 c. à soupe de gel", "1 verre d'eau pour la préparation"),
          ("Cheveux mi-longs (10 à 25 cm)", "2 c. à soupes de gel", "1 verre et demi"),
          ("Cheveux longs (plus de 25 cm)", "4 c. à soupes de gel", "2 verres")],
     qte_note="Base : <b>5 à 6 gombos frais pour 1 verre d'eau (250 ml)</b>. Le liquide doit être glissant entre les "
              "doigts, comme un blanc d'œuf.",
     recette_titre="Le gel de gombo (3 ingrédients)",
     recette=["5 à 6 gombos frais, coupés en fines rondelles",
              "1 verre d'eau (250 ml)",
              "1 c. à café de miel (facultatif, pour l'hydratation)"],
     recette_note="Laissez tremper une nuit (ou 2 heures minimum), puis filtrez à travers un bas nylon propre en "
                  "pressant bien. Remplissez un flacon propre. Au réfrigérateur : 3 à 5 jours, pas plus.",
     etapes=["Mouillez les cheveux à l'eau tiède.",
             "Séparez en 4 sections. Appliquez le gel mèche par mèche, des pointes vers les racines.",
             "Démêlez au peigne à dents larges, sur cheveux bien glissants, en tenant la base de la mèche.",
             "Laissez poser 15 à 20 minutes puis rincez à l'eau tiède — ou laissez sécher pour coiffer."],
     freq=[("Routine normale", "1 fois par semaine"),
           ("Cheveux très emmêlés, enfants", "2 fois par semaine"),
           ("En sans-rinçage au coiffage", "1 fois par semaine"),
           ("Conservation maximale", "3 à 5 jours au frigo")],
     precautions=["Après 5 jours au frigo, jetez : ça fermente et ça sent aigre.",
                  "Filtrez finement : les petits morceaux s'accrochent et cassent le cheveu.",
                  "Ne mélangez pas le gombo avec du vinaigre : le gel perd son glissant."],
     erreurs=["En mettre « beaucoup » : au-delà de la dose, ça laisse un film collant.",
              "Filtrer au chinois large : les morceaux restent.",
              "Le laisser dehors à la chaleur : en une journée, ce n'est plus un soin, c'est un bouillon."],
     conservation="3 à 5 jours au réfrigérateur, dans un flacon fermé. Usage immédiat après filtration.",
     retiens="Le gombo ne nourrit pas le cheveu : il le fait glisser. Or c'est au démêlage qu'on perd le plus de cheveux."),

dict(num=6, nom="Les graines de lin", sci="Linum usitatissimum · brunes ou dorées",
     famille="Gels et mucilages", preuve="tradition", cout="≈ 100 FCFA l'application", pose="séchage à l'air",
     pourquoi="Au contact de l'eau chaude, les graines libèrent un gel de sucres complexes. Ce gel forme un filet "
              "autour du cheveu : il fait glisser les mèches au démêlage et, en séchant, il <b>fixe la boucle</b> "
              "sans effet carton et sans silicone. C'est un gel coiffant honnête, à 100 FCFA le flacon, qui tient "
              "les vanilles et les twists sans les raidir.",
     cible=["Types 3C et 4", "Vanilles et twists", "Cheveux fins à moyens", "Coiffage sans chaleur"],
     qte=[("Gel à utiliser — cheveux courts", "1 c. à soupe", "préparation : 2 c. à soupes de graines / 1 verre d'eau"),
          ("Gel à utiliser — cheveux mi-longs", "2 c. à soupes", "préparation identique"),
          ("Gel à utiliser — cheveux longs", "4 c. à soupes", "préparation identique")],
     qte_note="Un verre d'eau donne environ 250 ml de gel : c'est la dose pour 2 à 3 coiffages.",
     recette_titre="Le gel de lin",
     recette=["2 c. à soupes de graines de lin entières",
              "1 verre d'eau (250 ml)",
              "1 c. à café de miel (facultatif)"],
     recette_note="Portez à petite ébullition 8 à 10 minutes en remuant — le liquide doit devenir sirupeux. "
                  "Laissez tiédir, puis filtrez dans un bas nylon en pressant. Remplissez un flacon propre, au frigo.",
     etapes=["Hydratez les cheveux (lavés ou vaporisés) et sectionnez.",
             "Appliquez le gel en travaillant des pointes vers les racines.",
             "Enroulez les boucles autour du doigt ou coiffez en vanilles serrées à la base, souples au bout.",
             "Laissez sécher à l'air libre, sans toucher : c'est le séchage qui fixe la forme."],
     freq=[("Coiffage", "1 à 2 fois par semaine"),
           ("Conservation au frigo", "1 à 2 semaines"),
           ("Sorti du frigo", "une journée maximum"),
           ("Cheveux secs", "avec 1 c. à café d'huile ajoutée au gel")],
     precautions=["Graines fraîches obligatoires : des graines trop vieilles ne gélifient pas.",
                  "Odeur aigre ou filaments bizarres : jetez immédiatement.",
                  "Trop de gel : le cheveu devient figé et attire la poussière."],
     erreurs=["Coiffer sur cheveux détrempés : la boucle ne tient pas.",
              "Garder le gel plus de deux semaines.",
              "Filtrer à la passoire : les graines passent et restent coincées dans les cheveux."],
     conservation="1 à 2 semaines au réfrigérateur dans un flacon fermé.",
     retiens="Un gel qui fixe sans durcir, fabriqué avec deux cuillères de graines."),

dict(num=7, nom="L'aloé vera", sci="Aloe vera (Aloe barbadensis) · feuille fraîche",
     famille="Gels et mucilages", preuve="tradition", cout="≈ 100 FCFA (feuille) ou gratuit au jardin", pose="sans rinçage",
     pourquoi="Le gel de la feuille contient près de 98 % d'eau, chargée de sucres complexes et de composés apaisants. "
              "Sur le cuir chevelu, c'est un excellent hydratant : il calme les démangeaisons et les tiraillements "
              "d'une pose de tresses, et laisse le crâne souple au lieu de le faire tirer. Attention : il ne scelle pas. "
              "Appliqué seul et laissé à sécher, il peut dessécher. On le couvre donc toujours de quelques gouttes d'huile.",
     cible=["Crâne sec ou qui gratte", "Sous les tresses", "Pellicules sèches", "Après une dépose"],
     qte=[("Gel frais pour le crâne", "1 c. à soupe", "toutes longueurs"),
          ("Huile légère pour sceller", "1 c. à café", "coco ou olive"),
          ("En masque pour les longueurs", "2 à 4 c. à soupes", "selon la longueur")],
     qte_note="Une feuille moyenne donne 2 à 4 c. à soupes de gel : largement de quoi faire deux applications.",
     recette_titre="Le spray du crâne sous tresses",
     recette=["4 c. à soupes de gel d'aloé frais",
              "1 verre d'eau (250 ml)",
              "1 c. à café d'huile de coco fondue"],
     recette_note="Versez le tout dans un flacon spray propre et gardez-le au réfrigérateur. Secouez avant chaque "
                  "utilisation. À consommer en 5 à 7 jours.",
     etapes=["Coupez une feuille, retirez les épines, laissez-la égoutter 10 minutes : la sève jaune qui sort irrite.",
             "Épluchez la feuille et prélevez le gel transparent, sans la partie verte.",
             "Appliquez sur le crâne et massez 2 minutes du bout des doigts.",
             "Scellez avec 2 à 3 gouttes d'huile — c'est ce qui garde l'eau dans le crâne."],
     freq=[("Crâne sec ou qui gratte", "2 à 3 fois par semaine"),
           ("Pendant une pose de tresses", "2 fois par semaine"),
           ("Masque des longueurs", "1 fois par semaine"),
           ("Conservation", "5 à 7 jours au frigo")],
     precautions=["La sève jaune (aloïne) irrite et tache : rincez-la avant d'utiliser le gel.",
                  "Utilisez uniquement l'aloé vera ; certaines variétés d'aloès ne s'emploient pas sur la peau.",
                  "Si une sensation d'étirement apparaît après séchage, c'est que vous n'avez pas scellé : ajoutez l'huile."],
     erreurs=["Acheter un gel « à l'aloé vera » en sachet : il contient surtout de l'eau, du sucre et du colorant.",
              "Laisser sécher l'aloé seul sur le crâne : il hydrate puis assèche.",
              "L'appliquer sur une plaie ou une zone à vif."],
     conservation="Feuille entière : 2 à 3 semaines au frais. Gel prélevé : 5 à 7 jours au réfrigérateur.",
     retiens="L'aloé apporte l'eau, l'huile la retient. Les deux ensemble, jamais l'un sans l'autre."),

dict(num=8, nom="Le miel", sci="Miel cru et local, non pasteurisé, sans additif",
     famille="Hydratants", preuve="prometteur", cout="≈ 40 FCFA l'application", pose="20 min",
     pourquoi="Le miel est un <b>humectant</b> : comme la glycérine, il attire l'humidité de l'air et la retient dans "
              "le cheveu. Il adoucit aussi la cuticule, ce qui rend le démêlage plus facile. Une précaution de bon sens : "
              "pendant le harmattan, l'air est si sec qu'il n'y a presque rien à attirer — mettez alors très peu de miel, "
              "et scellez toujours avec un beurre ou une huile, sinon l'effet s'inverse.",
     cible=["Cheveux secs et rêches", "Cheveux difficiles à démêler", "Tous types", "Dans tous les masques"],
     qte=[("Dans un masque", "1 c. à café pour 2 c. à soupes de base", "≈ 4 g"),
          ("Masque au miel seul, cheveux courts", "1 c. à soupe", "avec 1 c. à café d'huile"),
          ("Masque au miel seul, cheveux mi-longs et longs", "2 c. à soupes", "avec 1 c. à soupe d'huile")],
     qte_note="Le miel pur et local (non coupé au sirop) est le seul qui travaille. S'il est cristallisé, "
              "c'est bon signe : tiédissez-le au bain-marie.",
     recette_titre="Le masque d'urgence « sec-paille »",
     recette=["2 c. à soupes de miel",
              "2 c. à soupes de yaourt nature entier",
              "1 c. à soupe d'huile d'olive"],
     recette_note="Mélangez à la cuillère jusqu'à obtenir une crème lisse. Pose : 20 minutes sous un bonnet. "
                  "À faire quand le cheveu craque et refuse de se démêler.",
     etapes=["Travaillez sur cheveux essorés : humides, mais pas dégoulinants.",
             "Appliquez en sections, du crâne vers les pointes.",
             "Couvrez d'un bonnet et laissez poser 20 minutes — pas une heure.",
             "Rincez à l'eau tiède, puis scellez avec une noix de karité."],
     freq=[("Dans un masque", "1 fois par semaine"),
           ("Masque au miel seul", "1 fois par 15 jours"),
           ("Tous les jours", "jamais : cheveu collant qui attire la poussière")],
     precautions=["Miel pur uniquement : les mélanges « miel » sucrés n'ont aucun effet.",
                  "Miel et nourrissons : ne laissez jamais un pot de miel à portée d'un bébé (risque de botulisme).",
                  "En climat très sec, divisez la dose par deux et scellez systématiquement."],
     erreurs=["En mettre une demi-tasse « pour que ça marche ».",
              "Laisser poser deux heures puis rincer à l'eau chaude : ça colle et ça assèche.",
              "Oublier de sceller après : le miel appelle l'eau, il ne la garde pas."],
     conservation="Le miel ne s'abîme pas. En mélange, la préparation se garde 3 jours au frigo.",
     retiens="Le miel apporte l'eau. C'est le beurre qui ferme la porte."),

dict(num=9, nom="L'œuf", sci="Œuf de poule entier · jaune et blanc",
     famille="Protéines et ferments", preuve="prometteur", cout="≈ 150 FCFA l'application", pose="15 à 20 min",
     pourquoi="Le jaune apporte des protéines et de la lécithine, qui émulsionne l'huile et l'eau ; le blanc apporte "
              "des protéines plus petites, qui se déposent sur les zones abîmées de la cuticule. Le cheveu paraît plus "
              "épais et plus résistant — mais c'est un effet de surface, <b>temporaire</b>. Un soin protéiné mal dosé "
              "durcit le cheveu : il devient sec, rêche et cassant. C'est pour cela que c'est le seul ingrédient de ce "
              "guide qu'on utilise une fois par mois, pas plus.",
     cible=["Cheveux cassants", "Après défrisage ou coloration", "Cheveu « mou » qui s'étire comme un chewing-gum", "Fibre abîmée par la chaleur"],
     qte=[("Cheveux courts (moins de 10 cm)", "1 œuf + 1 c. à soupe d'huile + 1 c. à café de miel", "temps de pose : 15 min"),
          ("Cheveux mi-longs (10 à 25 cm)", "1 œuf + 2 c. à soupes d'huile + 1 c. à café de miel", "20 min"),
          ("Cheveux longs (plus de 25 cm)", "2 œufs + 2 c. à soupes d'huile + 1 c. à soupe de miel", "20 min maximum")],
     qte_note="<b>Jamais plus de 20 minutes</b>, et jamais deux semaines de suite.",
     recette_titre="Le masque protéiné simple",
     recette=["1 œuf entier",
              "1 c. à soupe d'huile d'olive (ou de coco)",
              "1 c. à café de miel  ·  facultatif : 1 c. à soupe de yaourt"],
     recette_note="Battez à la fourchette jusqu'à ce que le mélange soit parfaitement homogène : des morceaux de blanc "
                  "coagulés sont impossibles à démêler.",
     etapes=["Appliquez sur cheveux propres et essorés, en sections.",
             "Ne massez pas fort : on dépose le soin, on ne frotte pas.",
             "Posez 15 à 20 minutes, <b>sans chaleur</b> : pas de bonnet chauffant, pas de sèche-cheveux.",
             "Rincez à l'eau <b>tiède</b> pendant 3 à 5 minutes, puis enchaînez sur un masque hydratant."],
     freq=[("Routine normale", "1 fois par mois"),
           ("Cheveux très abîmés", "2 fois par mois, espacées de 15 jours"),
           ("Après le soin protéiné", "masque hydratant obligatoire dans la même séance"),
           ("Deux semaines de suite", "jamais")],
     precautions=["Rinçage à l'eau tiède obligatoire : à l'eau chaude, l'œuf cuit dans les cheveux.",
                  "Allergie à l'œuf : n'utilisez pas ce soin, même en petite dose.",
                  "Jetez tout reste : un mélange à l'œuf ne se conserve pas, même au frais."],
     erreurs=["Laisser poser une heure « pour plus d'effet » → cheveu dur et cassant.",
              "Rincer à l'eau chaude → petits morceaux de blanc dans les cheveux.",
              "En faire chaque semaine « pour réparer plus vite » → c'est l'inverse qui se produit."],
     conservation="À utiliser immédiatement. Aucune conservation possible.",
     retiens="Un soin protéiné n'est pas un soin de plus, c'est un soin à part : une fois par mois, suivi d'hydratation."),

dict(num=10, nom="Le yaourt nature", sci="Yaourt entier nature, sans sucre ni arôme",
     famille="Hydratants et nettoyants", preuve="tradition", cout="≈ 120 FCFA l'application", pose="20 min",
     pourquoi="Le yaourt est <b>acide</b> (pH ≈ 4,4). Cet acide referme les écailles ouvertes par l'eau et le savon, "
              "dissout les dépôts de calcaire et de produits, et laisse le cheveu doux et brillant. Ses ferments "
              "nettoient le cuir chevelu sans le décaper, comme le ferait un savon. C'est le soin à connaître quand "
              "le crâne gratte, quand les pellicules sont grasses et que le cheveu paraît terne.",
     cible=["Pellicules grasses", "Crâne qui gratte", "Cheveu terne", "Après un lavage au savon noir"],
     qte=[("Cheveux courts (moins de 10 cm)", "2 c. à soupes de yaourt", "+ 1 c. à café de miel"),
          ("Cheveux mi-longs (10 à 25 cm)", "4 c. à soupes de yaourt", "+ 1 c. à soupe de miel"),
          ("Cheveux longs (plus de 25 cm)", "6 c. à soupes de yaourt", "+ 1 c. à soupe de miel")],
     qte_note="Un pot de yaourt de 125 g ≈ 8 c. à soupes : il suffit pour un masque longueurs + crâne.",
     recette_titre="Le masque yaourt-miel",
     recette=["4 c. à soupes de yaourt nature entier",
              "1 c. à soupe de miel",
              "1 c. à café d'huile d'olive"],
     recette_note="Sortez le yaourt du réfrigérateur 10 minutes avant : un soin glacé fait mal au cuir chevelu.",
     etapes=["Appliquez sur cheveux humides, du crâne jusqu'aux pointes.",
             "Massez 2 minutes du bout des doigts pour faire travailler les ferments sur le crâne.",
             "Laissez poser 20 minutes sous un bonnet.",
             "Rincez abondamment à l'eau tiède ; si l'odeur persiste, un rinçage acide léger la fait disparaître."],
     freq=[("Routine", "1 fois par 2 semaines"),
           ("Jamais", "plus d'une fois par semaine"),
           ("À éviter", "juste avant une sortie (odeur)")],
     precautions=["Rinçage soigneux : les résidus de lait fermentent et sentent.",
                  "Ne l'appliquez pas sur un crâne à vif, irrité ou couvert de plaies.",
                  "Yaourt nature uniquement : les yaourts sucrés et aromatisés nourrissent les microbes, pas les cheveux."],
     erreurs=["Utiliser un yaourt sucré ou aromatisé.",
              "Laisser poser une heure.",
              "Sauter le rinçage ou rincer à l'eau froide : le film gras reste."],
     conservation="Préparation à usage immédiat. Pot entamé : 2 jours au frigo.",
     retiens="Acide, donc lissant : c'est le seul ingrédient du guide qui nettoie et lisse en même temps."),

dict(num=11, nom="Le savon noir", sci="Savon africain · cendres de cacao, de palmiste ou de karité",
     famille="Nettoyants", preuve="tradition", cout="≈ 20 FCFA l'application", pose="1 à 2 min de moussage",
     pourquoi="Le savon noir nettoie très fort : il dégraisse le crâne, retire les résidus d'huile et de produits, et "
              "laisse la racine « respirer ». Mais son pH est élevé (souvent 9 à 10) : il soulève les écailles. "
              "Utilisé pur, semaine après semaine, il rend le cheveu rêche, terne et cassant. D'où les deux règles "
              "du guide : <b>toujours dilué</b>, et <b>toujours suivi d'un rinçage acide</b>.",
     cible=["Crâne gras", "Cheveux qui accumulent les résidus", "Après une longue période de tresses", "Pellicules grasses"],
     qte=[("Dose de savon", "1 c. à café rase", "pour 1 verre d'eau tiède (250 ml)"),
          ("Miel pour adoucir (facultatif)", "1 c. à café", "dans le même verre"),
          ("Cheveux courts", "½ verre du mélange", "1 seul lavage"),
          ("Cheveux longs", "1 verre entier", "insistez sur le crâne, pas sur les pointes")],
     qte_note="Le savon noir mousse peu : c'est normal. Doubler la dose n'améliore pas le lavage, ça abîme le cheveu.",
     recette_titre="Le shampooing doux au savon noir",
     recette=["1 c. à café rase de savon noir (râpé ou en pâte)",
              "1 verre d'eau tiède (250 ml)",
              "1 c. à café de miel (facultatif, pour adoucir)"],
     recette_note="Faites dissoudre en secouant dans un flacon. Cette dose sert pour un lavage complet. "
                  "Se garde 5 jours au frais.",
     etapes=["Mouillez abondamment : le savon noir a besoin d'eau.",
             "Versez le mélange au flacon applicateur sur le crâne et moussez 1 à 2 minutes du bout des doigts, jamais avec les ongles.",
             "Rincez à l'eau tiède jusqu'à ce que l'eau devienne claire (comptez 2 à 3 minutes).",
             "Terminez par le rinçage acide : 1 c. à soupe de vinaigre de cidre dans 1 verre d'eau, puis rincez."],
     freq=[("Crâne gras", "1 fois par semaine"),
           ("Crâne normal ou sec", "1 fois par 2 semaines"),
           ("Après une dépose de tresses", "1 fois, pour repartir propre"),
           ("Pur, ou sans rinçage acide", "jamais")],
     precautions=["Jamais pur sur le crâne : il brûle et laisse le cheveu rêche.",
                  "Peut ternir les cheveux colorés : réservez-le au crâne, ou espacez.",
                  "À éviter si le crâne est à vif, irrité ou couvert de pellicules sèches : cela aggrave."],
     erreurs=["Frotter avec les ongles : micro-plaies et boutons assurés.",
              "Doubler la dose parce que « ça ne mousse pas ».",
              "Sauter le rinçage acide : le cheveu reste rêche pendant des jours."],
     conservation="Le morceau de savon se garde plusieurs mois au sec. Le mélange préparé : 5 jours au frigo.",
     retiens="Le savon noir lave fort. Fort n'est pas un compliment : on le tempère toujours par un rinçage acide."),

dict(num=12, nom="Le vinaigre de cidre", sci="Vinaigre de cidre non filtré · acidité 5 %",
     famille="Acides", preuve="prometteur", cout="≈ 45 FCFA l'application", pose="30 secondes, sans pose",
     pourquoi="Dilué, le vinaigre a un pH acide qui <b>referme les écailles</b> que l'eau, la chaleur ou le savon ont "
              "ouvertes. Il dissout aussi les dépôts de calcaire laissés par une eau dure (puits, forage, robinet très "
              "minéralisée) — et ces dépôts sont une cause très fréquente de cheveu terne, rêche, « qui ne prend plus "
              "les soins ». L'effet est immédiat : le cheveu devient lisse, brillant, et s'emmêle moins.",
     cible=["Eau dure, puits ou forage", "Cheveux ternes", "Après un lavage au savon noir", "Cheveux qui ne prennent plus les soins"],
     qte=[("Cheveux courts à mi-longs", "1 c. à soupe pour 1 verre d'eau", "soit environ 15 ml pour 250 ml"),
          ("Cheveux longs ou très denses", "2 c. à soupes pour 1 verre d'eau", "ne dépassez pas"),
          ("Eau très calcaire", "1 c. à soupe et demie", "à ajuster en fonction du résultat")],
     qte_note="Ce n'est pas un masque : on verse, on masse 30 secondes, on rince. Jamais plus fort, jamais plus longtemps.",
     recette_titre="Le rinçage acide",
     recette=["1 c. à soupe de vinaigre de cidre",
              "1 verre d'eau fraîche (250 ml)",
              "facultatif : 3 gouttes d'huile essentielle de lavande, pour l'odeur"],
     recette_note="Préparez dans un pichet ou une bouteille au moment du rinçage. L'odeur de vinaigre disparaît "
                  "complètement au séchage.",
     etapes=["Après le shampooing et le masque, essorez les cheveux sans frotter.",
             "Versez le mélange lentement sur les longueurs (le crâne n'en a pas besoin).",
             "Massez 30 secondes : vous sentirez les écailles se lisser sous vos doigts.",
             "Rincez immédiatement à l'eau fraîche. Ne laissez pas poser."],
     freq=[("Routine", "1 fois par semaine à 1 fois par mois"),
           ("Après chaque lavage au savon noir", "systématiquement"),
           ("Deux jours de suite", "jamais"),
           ("Cheveux très secs", "1 fois par mois seulement")],
     precautions=["Jamais pur, jamais en pose longue : le cheveu durcit et devient rêche.",
                  "Pas sur un crâne à vif : ça pique et ça irrite.",
                  "Vinaigre de cidre (alimentaire), pas le vinaigre blanc industriel, réservé au ménage."],
     erreurs=["Confondre rinçage et masque : c'est un passage rapide, pas une pose.",
              "Augmenter la dose « pour plus de brillance » : l'effet s'inverse.",
              "Le verser avant le masque : il referme les écailles et bloque le soin."],
     conservation="Bouteille fermée : plusieurs mois, à l'abri de la lumière.",
     retiens="C'est le geste de finition : il ferme la porte que le lavage a ouverte."),
]

# ---------------------------------------------------------------- BONUS
BONUS = dict(
    num="+1", nom="L'eau de riz fermentée", sci="Eau de trempage et de fermentation du riz",
    famille="Protéines et ferments", preuve="prometteur", cout="≈ 100 FCFA (½ verre de riz)", pose="24 h de fermentation",
    pourquoi="Pendant la fermentation, le riz libère dans l'eau des minéraux (magnésium, zinc, silice) et des acides "
             "aminés. En rinçage, cette eau laisse un cheveu plus ferme, plus glissant, plus brillant. On l'appelle "
             "« l'eau de beauté de grand-mère » dans plusieurs pays d'Asie. Les essais scientifiques existent mais "
             "restent de qualité limitée : on la classe donc en <b>piste prometteuse</b>, pas en certitude.",
    cible=["Cheveux mous, sans ressort", "Cheveux cassants", "En cure", "Après un été ou une saison de tresses"],
    qte=[("Riz", "½ verre de riz cru", "rincez-le une fois à l'eau claire"),
         ("Eau", "2 verres d'eau (500 ml)", "eau de préférence filtrée"),
         ("Application", "1 verre du liquide fermenté", "en dernier rinçage"),
         ("Fréquence maximale", "1 à 2 fois par mois", "réduisez si le cheveu devient sec")],
    qte_note="Comme tous les soins riches en protéines et minéraux : trop souvent, le cheveu devient raide et cassant.",
    recette_titre="L'eau de riz fermentée",
    recette=["½ verre de riz (le riz de tous les jours)",
             "2 verres d'eau propre",
             "rien d'autre"],
    recette_note="Rincez le riz une fois, jetez cette première eau. Couvrez de 2 verres d'eau et laissez fermenter "
                 "18 à 24 heures à température ambiante, à couvert. Filtrez, gardez le liquide au frais 3 à 4 jours.",
    etapes=["Faites votre shampooing et votre masque comme d'habitude.",
             "Rincez abondamment à l'eau claire.",
             "Versez l'eau de riz sur les longueurs en dernier rinçage, massez 1 minute.",
             "Rincez légèrement à l'eau fraîche (ou laissez, si l'odeur ne vous gêne pas), puis scellez."],
    freq=[("Cure", "1 fois par mois, 2 fois maximum"),
           ("Conservation", "3 à 4 jours au réfrigérateur"),
           ("Cheveu qui devient raide", "arrêtez un mois"),
           ("Enfants", "déconseillé avant 10 ans (risque de fermentation sur le crâne)")],
    precautions=["Odeur aigre trop forte : jetez, la fermentation a mal tourné.",
                  "Ne laissez jamais fermenter dehors sans couvercle : poussières, insectes.",
                  "Si le cheveu devient sec et raide, c'est le signe d'un excès : espacez à un mois et demi."],
    erreurs=["En faire toutes les semaines : le cheveu se raidit.",
              "Utiliser l'eau de cuisson du riz salée ou épicée.",
              "La garder plus de 4 jours : elle tourne."],
    conservation="3 à 4 jours au réfrigérateur, dans un bocal fermé.",
    retiens="Une cure, pas une routine : une fois par mois, le cheveu paraît plus ferme.")

# ---------------------------------------------------------------- COMBINAISONS & ASTUCES
# clés = numéro de fiche : (à combiner avec, à éviter, astuce de terrain)
COMBINE = {
1: ("Le miel (hydratation) et le beurre de karité (scellage) après le rinçage.",
    "Le savon noir pur, qui annule le bénéfice protecteur du film d'huile.",
    "En saison sèche, gardez ½ c. à café dans un petit flacon au sac : trois gouttes sur les pointes avant de sortir."),
2: ("Toujours après un liquide : eau, spray d'aloé, ou juste après le rinçage.",
    "L'huile seule sur cheveu sec, ou deux beurres empilés (effet gras étouffé).",
    "Fouettez votre beurre une fois par mois : il devient plus léger, s'étale mieux, et vous en utiliserez moins."),
3: ("Une huile fluide (coco, olive, sésame) : 1 part de ricin pour 2 parts d'huile légère.",
    "L'usage pur sur le crâne, et l'application juste avant une sortie poussiéreuse.",
    "Pour la lisière : trempez un coton-tige dans le mélange et tapotez — vous en mettrez moins, et au bon endroit."),
4: ("Le miel (humectant) et une chaleur douce (bonnet, serviette tiède).",
    "La chaleur forte et la pose prolongée : au-delà de 30 minutes, le bénéfice ne grandit plus.",
    "Une huile d'olive qui pique légèrement la gorge est une vraie huile d'olive ; si elle est fade, elle est coupée."),
5: ("Le miel dans la préparation, et une huile légère en finition pour sceller.",
    "Le vinaigre dans la même préparation : le gel perd son glissant.",
    "Préparez la veille au soir : la filtration du matin est plus facile et le gel plus épais."),
6: ("Les huiles légères (coco) et le beurre de karité pour sceller après séchage.",
    "Le peigne fin sur cheveux secs après le gel : vous détruirez la définition.",
    "Twistez sur cheveux bien humides et laissez sécher sans toucher : la définition vient du séchage, pas du produit."),
7: ("Toujours une huile par-dessus, 2 à 3 gouttes suffisent.",
    "La pose longue en plein soleil, et l'application sur une plaie.",
    "Sous tresses : vaporisez le spray, puis tapotez avec le bout des doigts entre les raies, jamais en frottant."),
8: ("Le yaourt (acidité) et une huile ou un beurre pour sceller.",
    "Le bain-marie bouillant : au-delà de 40 °C, le miel perd ses enzymes et devient collant.",
    "S'il est cristallisé, c'est du vrai miel : 3 minutes dans de l'eau chaude et il redevient liquide."),
9: ("Un masque hydratant dans la même séance, juste après le rinçage.",
    "La chaleur (bonnet chauffant, sèche-cheveux) : l'œuf cuirait dans le cheveu.",
    "Battez longuement à la fourchette : un mélange bien lisse évite les morceaux de blanc impossibles à démêler."),
10: ("Le miel, et un rinçage acide léger si l'odeur persiste.",
     "Un crâne à vif, irrité, ou couvert de plaies.",
     "Sortez le yaourt du réfrigérateur dix minutes avant : un soin glacé fait mal au cuir chevelu."),
11: ("Un rinçage acide au vinaigre de cidre dans les deux minutes qui suivent.",
     "Frotter avec les ongles, doubler la dose, ou sauter le rinçage acide.",
     "Le savon noir mousse peu : c'est normal. La mousse n'est pas la propreté."),
12: ("En dernier rinçage, après le masque, avant le scellage.",
     "La pose longue, la concentration forte, et le vinaigre blanc industriel.",
     "Versez lentement, en filet, sur les longueurs : vous sentirez les écailles se refermer sous les doigts."),
"+1": ("Un rinçage acide après, puis un scellage à l'huile ou au beurre.",
       "L'usage hebdomadaire, et l'eau de cuisson salée ou épicée.",
       "Une fois par mois, pas plus : c'est une cure, pas un geste quotidien."),
}
